<?php
/**
 * Entity Manager dashboard: the data side (counters and health checks).
 *
 * Everything the dashboard shows is computed here, from two plain inputs, so it
 * can be tested without a database:
 *
 * - the normalized configuration (see glinf_get_config());
 * - a "context": the facts about the site that only WordPress knows (rewrite
 *   rules, permalink structure, registered routes, pages with the same path,
 *   customized templates). dashboard.php builds it with a handful of reads; a test
 *   builds it by hand. A key that is missing means "nothing to report" for the
 *   checks that need it, never an error.
 *
 * Nothing here reads a superglobal, queries the database or writes anything. The
 * functions return raw, unescaped plain text (names come from the configuration
 * or from the database): escaping is done where they are printed.
 *
 * A "health check" is an array:
 *
 *     array(
 *         'id'       => string,  // stable identifier, e.g. "rewrite_stale"
 *         'severity' => string,  // "warning" or "notice"
 *         'message'  => string,  // what it means and what to do (translatable)
 *         'items'    => array<int, array{label: string, code: string, detail: string, links: array<int, array{label: string, url: string, sr: string}>}>,
 *         'actions'  => array<int, array{label: string, url: string}>,
 *     )
 *
 * To add a check: write a `glinf_dashboard_check_<name>()` function that returns
 * such an array (or null when everything is fine), then call it from
 * glinf_dashboard_get_health_checks(). If it needs a new fact from WordPress, add
 * a key to the context in glinf_dashboard_normalize_context() (with a neutral
 * default) and fill it in glinf_dashboard_build_context().
 *
 * @package gl-infinite-theme
 */

declare(strict_types=1);

defined( 'ABSPATH' ) || exit;

/** Share of the maximum (in percent) from which the limit check starts to warn. */
const GLINF_DASHBOARD_LIMIT_NOTICE_PERCENT = 80;

/** Regex of the slugs of the templates generated by the theme (see templates.php). */
const GLINF_DASHBOARD_TEMPLATE_SLUG_REGEX = '/^(single|archive|taxonomy)-(glinf_[a-z0-9_]+)\z/';

/**
 * Builds one counter card.
 *
 * @param string $id    Stable identifier.
 * @param string $label Text under the number.
 * @param int    $value The number.
 * @param int    $max   Maximum, shown as "N of MAX" (0 = no maximum).
 * @param string $url   Filtered list this counter leads to ('' = no link).
 * @return array{id: string, label: string, value: int, max: int, url: string}
 */
function glinf_dashboard_stat( string $id, string $label, int $value, int $max = 0, string $url = '' ): array {
	return array(
		'id'    => $id,
		'label' => $label,
		'value' => $value,
		'max'   => $max,
		'url'   => $url,
	);
}

/**
 * Returns the counters of a screen.
 *
 * The numbers of the views ("With archive", "Shared", ...) come from
 * glinf_list_count_views(), the same function that prints the counts above the
 * list, so a card and its view can never disagree. A card links to its view only
 * when the view has something to show.
 *
 * @param string               $section "entities" or "taxonomies".
 * @param array<string, mixed> $config  Normalized configuration.
 * @param array<string, int>   $counts  Totals that need the database: `contents` (items of every entity) and `terms` (terms of every registered taxonomy).
 * @return array<int, array{id: string, label: string, value: int, max: int, url: string}>
 */
function glinf_dashboard_stats( string $section, array $config, array $counts ): array {
	if ( 'taxonomies' === $section ) {
		$views = glinf_list_count_views( 'taxonomies', glinf_list_build_taxonomy_rows( $config ) );

		return array(
			glinf_dashboard_stat( 'taxonomies', __( 'Taxonomies configured', 'gl-infinite-theme' ), count( $config['taxonomies'] ), GLINF_TAXONOMIES_MAX ),
			glinf_dashboard_stat( 'specific', __( 'Specific to one entity', 'gl-infinite-theme' ), $views['specific'], 0, glinf_dashboard_view_url( 'taxonomies', 'specific', $views['specific'] ) ),
			glinf_dashboard_stat( 'shared', __( 'Shared by several entities', 'gl-infinite-theme' ), $views['shared'], 0, glinf_dashboard_view_url( 'taxonomies', 'shared', $views['shared'] ) ),
			glinf_dashboard_stat( 'unattached', __( 'Not attached to any entity', 'gl-infinite-theme' ), $views['unattached'], 0, glinf_dashboard_view_url( 'taxonomies', 'unattached', $views['unattached'] ) ),
			glinf_dashboard_stat( 'terms', __( 'Terms in total', 'gl-infinite-theme' ), (int) ( $counts['terms'] ?? 0 ) ),
		);
	}

	$views = glinf_list_count_views( 'entities', glinf_list_build_entity_rows( $config ) );

	return array(
		glinf_dashboard_stat( 'entities', __( 'Entities configured', 'gl-infinite-theme' ), count( $config['items'] ), GLINF_ENTITIES_MAX ),
		glinf_dashboard_stat( 'contents', __( 'Content items in total', 'gl-infinite-theme' ), (int) ( $counts['contents'] ?? 0 ) ),
		glinf_dashboard_stat( 'archive', __( 'Entities with an archive', 'gl-infinite-theme' ), $views['archive'], 0, glinf_dashboard_view_url( 'entities', 'archive', $views['archive'] ) ),
		glinf_dashboard_stat( 'with_tax', __( 'Entities with taxonomies', 'gl-infinite-theme' ), $views['with_tax'], 0, glinf_dashboard_view_url( 'entities', 'with_tax', $views['with_tax'] ) ),
	);
}

/**
 * Returns the URL of a filtered view of a list, or '' when the view is empty.
 *
 * @param string $kind  "entities" or "taxonomies".
 * @param string $view  A key of glinf_list_get_view_labels().
 * @param int    $count Rows in the view.
 * @return string
 */
function glinf_dashboard_view_url( string $kind, string $view, int $count ): string {
	return $count > 0 ? glinf_entities_screen_url( $kind, array( 'view' => $view ) ) : '';
}

/**
 * Fills the context with neutral defaults and drops what has the wrong type.
 *
 * Neutral means "no problem to report": no rules known, no routes, no customized
 * templates, pretty permalinks.
 *
 * @param array<string, mixed> $context Raw context.
 * @return array{permalink_structure: string, rewrite_rules: array<string, string>, registered_routes: array<int, array{slug: string, owner: string, kind: string}>, content_paths: array<int, array{path: string, type: string, title: string, edit_url: string}>, custom_templates: string[], urls: array{permalinks: string, site_editor: string}}
 */
function glinf_dashboard_normalize_context( array $context ): array {
	$structure = isset( $context['permalink_structure'] ) && is_string( $context['permalink_structure'] ) ? trim( $context['permalink_structure'] ) : '/%postname%/';

	$rules = array();
	if ( isset( $context['rewrite_rules'] ) && is_array( $context['rewrite_rules'] ) ) {
		foreach ( $context['rewrite_rules'] as $pattern => $query ) {
			if ( ! is_string( $query ) ) {
				continue;
			}

			$pattern = (string) $pattern;

			// In "almost pretty" permalinks every key starts with the index file: compare without it.
			if ( str_starts_with( $pattern, 'index.php/' ) ) {
				$pattern = substr( $pattern, 10 );
			}

			$rules[ $pattern ] = $query;
		}
	}

	$routes = array();
	if ( isset( $context['registered_routes'] ) && is_array( $context['registered_routes'] ) ) {
		foreach ( $context['registered_routes'] as $route ) {
			if ( is_array( $route ) && isset( $route['slug'], $route['owner'] ) && is_string( $route['slug'] ) && is_string( $route['owner'] ) ) {
				$routes[] = array(
					'slug'  => $route['slug'],
					'owner' => $route['owner'],
					'kind'  => isset( $route['kind'] ) && 'taxonomy' === $route['kind'] ? 'taxonomy' : 'post_type',
				);
			}
		}
	}

	$paths = array();
	if ( isset( $context['content_paths'] ) && is_array( $context['content_paths'] ) ) {
		foreach ( $context['content_paths'] as $path ) {
			if ( is_array( $path ) && isset( $path['path'] ) && is_string( $path['path'] ) ) {
				$paths[] = array(
					'path'     => $path['path'],
					'type'     => isset( $path['type'] ) && 'post' === $path['type'] ? 'post' : 'page',
					'title'    => isset( $path['title'] ) && is_string( $path['title'] ) ? $path['title'] : '',
					'edit_url' => isset( $path['edit_url'] ) && is_string( $path['edit_url'] ) ? $path['edit_url'] : '',
				);
			}
		}
	}

	$templates = array();
	if ( isset( $context['custom_templates'] ) && is_array( $context['custom_templates'] ) ) {
		foreach ( $context['custom_templates'] as $slug ) {
			if ( is_string( $slug ) ) {
				$templates[] = $slug;
			}
		}
	}

	$urls = isset( $context['urls'] ) && is_array( $context['urls'] ) ? $context['urls'] : array();

	return array(
		'permalink_structure' => $structure,
		'rewrite_rules'       => $rules,
		'registered_routes'   => $routes,
		'content_paths'       => $paths,
		'custom_templates'    => array_values( array_unique( $templates ) ),
		'urls'                => array(
			'permalinks'  => isset( $urls['permalinks'] ) && is_string( $urls['permalinks'] ) ? $urls['permalinks'] : '',
			'site_editor' => isset( $urls['site_editor'] ) && is_string( $urls['site_editor'] ) ? $urls['site_editor'] : '',
		),
	);
}

/**
 * Flattens the configuration into one list of elements, entities first.
 *
 * `active` is true when the element is registered with WordPress: every entity
 * is; a taxonomy only when at least one entity is attached (see
 * glinf_register_taxonomy()). Only active elements can have a live URL, so only
 * they are checked for clashes and for missing rewrite rules.
 *
 * @param array<string, mixed> $config Normalized configuration.
 * @return array<int, array{kind: string, slug: string, name: string, key: string, base: string, active: bool, archive: bool, edit_url: string}>
 */
function glinf_dashboard_build_elements( array $config ): array {
	$elements = array();

	foreach ( $config['items'] as $entity ) {
		$elements[] = array(
			'kind'     => 'entity',
			'slug'     => $entity['slug'],
			'name'     => $entity['plural'],
			'key'      => glinf_entity_post_type( $entity['slug'] ),
			'base'     => glinf_entity_url_base( $entity ),
			'active'   => true,
			'archive'  => (bool) $entity['has_archive'],
			'edit_url' => glinf_entities_admin_url(
				array(
					'action' => 'edit',
					'entity' => $entity['slug'],
				)
			),
		);
	}

	foreach ( $config['taxonomies'] as $taxonomy ) {
		$elements[] = array(
			'kind'     => 'taxonomy',
			'slug'     => $taxonomy['slug'],
			'name'     => $taxonomy['plural'],
			'key'      => glinf_taxonomy_key( $taxonomy['slug'] ),
			'base'     => glinf_taxonomy_url_base( $taxonomy ),
			'active'   => array() !== $taxonomy['entities'],
			'archive'  => true,
			'edit_url' => glinf_taxonomies_admin_url(
				array(
					'action'         => 'edit',
					'glinf_taxonomy' => $taxonomy['slug'],
				)
			),
		);
	}

	return $elements;
}

/**
 * Builds the "Edit" link of an element (the name is read out by screen readers).
 *
 * @param array<string, mixed> $element Element from glinf_dashboard_build_elements().
 * @return array{label: string, url: string, sr: string}
 */
function glinf_dashboard_edit_link( array $element ): array {
	return array(
		'label' => __( 'Edit', 'gl-infinite-theme' ),
		'url'   => $element['edit_url'],
		'sr'    => $element['name'],
	);
}

/**
 * Builds one item of a check.
 *
 * @param string                                                     $label  Name shown in bold.
 * @param string                                                     $code   Technical identifier shown as code ('' for none).
 * @param string                                                     $detail Sentence(s) that explain it ('' for none).
 * @param array<int, array{label: string, url: string, sr: string}>  $links  Action links of the item.
 * @return array{label: string, code: string, detail: string, links: array<int, array{label: string, url: string, sr: string}>}
 */
function glinf_dashboard_item( string $label, string $code, string $detail, array $links = array() ): array {
	return array(
		'label'  => $label,
		'code'   => $code,
		'detail' => $detail,
		'links'  => $links,
	);
}

/**
 * Builds a check.
 *
 * @param string                                                                                                 $id       Stable identifier.
 * @param string                                                                                                 $severity "warning" or "notice".
 * @param string                                                                                                 $message  Explanation and what to do.
 * @param array<int, array{label: string, code: string, detail: string, links: array<int, array<string, string>>}> $items    Elements involved.
 * @param array<int, array{label: string, url: string}>                                                          $actions  Links that fix or explain it.
 * @return array{id: string, severity: string, message: string, items: array<int, array<string, mixed>>, actions: array<int, array{label: string, url: string}>}
 */
function glinf_dashboard_check( string $id, string $severity, string $message, array $items = array(), array $actions = array() ): array {
	return array(
		'id'       => $id,
		'severity' => $severity,
		'message'  => $message,
		'items'    => $items,
		'actions'  => $actions,
	);
}

/**
 * Builds the action link of a check, or nothing when its URL is unknown.
 *
 * @param string $label Link text.
 * @param string $url   Destination.
 * @return array<int, array{label: string, url: string}> One link, or an empty list.
 */
function glinf_dashboard_action( string $label, string $url ): array {
	return '' === $url ? array() : array(
		array(
			'label' => $label,
			'url'   => $url,
		),
	);
}

/**
 * Check: taxonomies attached to no entity.
 *
 * Such a taxonomy is kept in the configuration but is not registered, so it
 * disappears from the editor and from the front end. Its terms stay in the database.
 *
 * @param array<int, array<string, mixed>> $elements Elements (glinf_dashboard_build_elements()).
 * @return array<string, mixed>|null
 */
function glinf_dashboard_check_unattached( array $elements ): ?array {
	$items = array();

	foreach ( $elements as $element ) {
		if ( 'taxonomy' === $element['kind'] && ! $element['active'] ) {
			$items[] = glinf_dashboard_item( $element['name'], $element['key'], '', array( glinf_dashboard_edit_link( $element ) ) );
		}
	}

	if ( array() === $items ) {
		return null;
	}

	return glinf_dashboard_check(
		'unattached_taxonomies',
		'warning',
		__( 'These taxonomies are not attached to any entity, so they are not registered: they do not appear in the editor or on the site. Their terms are kept in the database. Attach each one to an entity to use it again.', 'gl-infinite-theme' ),
		$items
	);
}

/**
 * Tells whether a post can have a one-segment address, i.e. can shadow a URL base.
 *
 * Only the "/%postname%/" permalink structure gives a post the address
 * "/<slug>/". With any other structure (dates, category, ...) a post never sits
 * where an entity archive does, so it must not be reported.
 *
 * @param string $structure Value of the `permalink_structure` option.
 * @return bool
 */
function glinf_dashboard_posts_can_shadow( string $structure ): bool {
	$structure = trim( $structure, '/' );

	if ( str_starts_with( $structure, 'index.php/' ) ) {
		$structure = substr( $structure, 10 );
	}

	return '%postname%' === $structure;
}

/**
 * Check: the URL base of an element now clashes with something else.
 *
 * The validation of the forms only looks at the moment of saving; this looks at
 * the site as it is now. Three kinds of clash are reported, for active elements only:
 *
 * - another element of the configuration has the same base (only possible if the
 *   option was edited by hand);
 * - a post type or taxonomy of somebody else (a plugin, core) registers the same segment;
 * - a published page (or, with "/%postname%/" permalinks, a post) has that path.
 *
 * The routes registered by the theme's own entities and taxonomies are skipped: an
 * element's own route is not a clash with itself, and two of them with the same
 * base are already caught by the first rule.
 *
 * @param array<int, array<string, mixed>> $elements Elements (glinf_dashboard_build_elements()).
 * @param array<string, mixed>             $context  Normalized context.
 * @return array<string, mixed>|null
 */
function glinf_dashboard_check_url_conflicts( array $elements, array $context ): ?array {
	$own = array(
		'post_type' => array(),
		'taxonomy'  => array(),
	);
	foreach ( $elements as $element ) {
		$own[ 'entity' === $element['kind'] ? 'post_type' : 'taxonomy' ][ $element['key'] ] = true;
	}

	$items = array();

	foreach ( $elements as $element ) {
		if ( ! $element['active'] ) {
			continue;
		}

		$details = array();

		foreach ( $elements as $other ) {
			if ( ! $other['active'] || ( $other['kind'] === $element['kind'] && $other['slug'] === $element['slug'] ) ) {
				continue;
			}
			if ( $other['base'] === $element['base'] ) {
				/* translators: %s: name of another entity or taxonomy. */
				$details[] = sprintf( __( 'Same URL base as %s.', 'gl-infinite-theme' ), $other['name'] );
			}
		}

		foreach ( $context['registered_routes'] as $route ) {
			if ( $route['slug'] !== $element['base'] || isset( $own[ $route['kind'] ][ $route['owner'] ] ) ) {
				continue;
			}

			$details[] = 'taxonomy' === $route['kind']
				/* translators: %s: registered name of a taxonomy. */
				? sprintf( __( 'Already used by the taxonomy "%s".', 'gl-infinite-theme' ), $route['owner'] )
				/* translators: %s: registered name of a post type. */
				: sprintf( __( 'Already used by the post type "%s".', 'gl-infinite-theme' ), $route['owner'] );
		}

		$links = array( glinf_dashboard_edit_link( $element ) );

		foreach ( $context['content_paths'] as $content ) {
			if ( $content['path'] !== $element['base'] ) {
				continue;
			}
			if ( 'post' === $content['type'] && ! glinf_dashboard_posts_can_shadow( $context['permalink_structure'] ) ) {
				continue;
			}

			$details[] = 'post' === $content['type']
				/* translators: %s: title of a post. */
				? sprintf( __( 'A published post has the same address: "%s".', 'gl-infinite-theme' ), $content['title'] )
				/* translators: %s: title of a page. */
				: sprintf( __( 'A published page has the same address: "%s".', 'gl-infinite-theme' ), $content['title'] );

			if ( '' !== $content['edit_url'] ) {
				$links[] = array(
					'label' => 'post' === $content['type'] ? __( 'Edit post', 'gl-infinite-theme' ) : __( 'Edit page', 'gl-infinite-theme' ),
					'url'   => $content['edit_url'],
					'sr'    => $content['title'],
				);
			}
		}

		if ( array() !== $details ) {
			$items[] = glinf_dashboard_item( $element['name'], '/' . $element['base'] . '/', implode( ' ', array_unique( $details ) ), $links );
		}
	}

	if ( array() === $items ) {
		return null;
	}

	return glinf_dashboard_check(
		'url_conflicts',
		'warning',
		__( 'The URL base of these items now clashes with another address on the site, so one of the two may not be reachable. Change the URL base of the entity or taxonomy, or change the address of the other item.', 'gl-infinite-theme' ),
		$items
	);
}

/**
 * Tells whether the saved rewrite rules contain a rule of a route.
 *
 * A rule belongs to a route when its pattern starts with "<base>/" and its query
 * starts with the given text. The keys must be normalized (see
 * glinf_dashboard_normalize_context()).
 *
 * @param array<string, string> $rules       Rewrite rules, pattern => query.
 * @param string                $base        URL base.
 * @param string                $query_start Beginning of the query of the rule.
 * @param string                $exact       When not empty, the pattern must be exactly this.
 * @return bool
 */
function glinf_dashboard_rules_have( array $rules, string $base, string $query_start, string $exact = '' ): bool {
	foreach ( $rules as $pattern => $query ) {
		$pattern = (string) $pattern;
		$belongs = '' !== $exact ? $pattern === $exact : str_starts_with( $pattern, $base . '/' );

		if ( $belongs && str_starts_with( $query, $query_start ) ) {
			return true;
		}
	}

	return false;
}

/**
 * Check: the saved rewrite rules do not contain the URL of an element yet.
 *
 * WordPress rebuilds the rules when the permalinks settings are saved (and this
 * theme rebuilds them after every change of the configuration), so a gap means
 * the rules were not rebuilt since a change: the addresses answer "not found".
 * Nothing is reported when:
 *
 * - the permalinks are "Plain" (there are no rules to check: see the plain
 *   permalinks check);
 * - the rules are not known (the option is empty: WordPress builds them on the
 *   first visit of the site, so they cannot be judged from the admin).
 *
 * Every entity is expected to have the rule of its single items and, when it has
 * an archive, the rule of the archive; every active taxonomy the rule of its terms.
 *
 * @param array<int, array<string, mixed>> $elements Elements (glinf_dashboard_build_elements()).
 * @param array<string, mixed>             $context  Normalized context.
 * @param array<int, array<string, mixed>> $actions  Links of the check.
 * @return array<string, mixed>|null
 */
function glinf_dashboard_check_rewrite_rules( array $elements, array $context, array $actions ): ?array {
	if ( '' === $context['permalink_structure'] || array() === $context['rewrite_rules'] ) {
		return null;
	}

	$rules = $context['rewrite_rules'];
	$items = array();

	foreach ( $elements as $element ) {
		if ( ! $element['active'] ) {
			continue;
		}

		$base    = $element['base'];
		$missing = array();

		if ( 'entity' === $element['kind'] ) {
			if ( ! glinf_dashboard_rules_have( $rules, $base, 'index.php?' . $element['key'] . '=' ) ) {
				$missing[] = __( 'The rule for the single items is missing.', 'gl-infinite-theme' );
			}
			if ( $element['archive'] && ! glinf_dashboard_rules_have( $rules, $base, 'index.php?post_type=' . $element['key'], $base . '/?$' ) ) {
				$missing[] = __( 'The rule for the archive is missing.', 'gl-infinite-theme' );
			}
		} elseif ( ! glinf_dashboard_rules_have( $rules, $base, 'index.php?' . $element['key'] . '=' ) ) {
			$missing[] = __( 'The rule for the term archives is missing.', 'gl-infinite-theme' );
		}

		if ( array() !== $missing ) {
			$items[] = glinf_dashboard_item( $element['name'], '/' . $base . '/', implode( ' ', $missing ) );
		}
	}

	if ( array() === $items ) {
		return null;
	}

	return glinf_dashboard_check(
		'rewrite_stale',
		'warning',
		__( 'The rewrite rules saved in the database do not include the address of these items yet, so their pages may show "not found". Open the permalink settings and click "Save Changes" (nothing needs to be changed) to rebuild the rules.', 'gl-infinite-theme' ),
		$items,
		$actions
	);
}

/**
 * Check: the permalinks are "Plain".
 *
 * With plain permalinks the pretty addresses of the entities and taxonomies
 * (such as /players/) are not used at all: items are reached with addresses
 * like ?glinf_player=name.
 *
 * @param array<string, mixed> $config  Normalized configuration.
 * @param array<string, mixed> $context Normalized context.
 * @return array<string, mixed>|null
 */
function glinf_dashboard_check_plain_permalinks( array $config, array $context ): ?array {
	if ( '' !== $context['permalink_structure'] || ( array() === $config['items'] && array() === $config['taxonomies'] ) ) {
		return null;
	}

	return glinf_dashboard_check(
		'plain_permalinks',
		'notice',
		__( 'The permalinks are set to "Plain": the readable addresses of your entities and taxonomies (such as /players/) do not work. Choose another structure, for example "Post name", in the permalink settings.', 'gl-infinite-theme' ),
		array(),
		glinf_dashboard_action( __( 'Open permalink settings', 'gl-infinite-theme' ), $context['urls']['permalinks'] )
	);
}

/**
 * Check: templates saved in the database for the theme's generated templates.
 *
 * A row of `wp_template` (a template saved from the Site Editor) with one of the
 * theme's generated slugs falls in one of two groups:
 *
 * - it matches a template that is still generated (an entity's single or archive,
 *   an attached taxonomy's terms): it REPLACES the generated one, which is no
 *   longer updated when the settings change;
 * - it matches nothing any more (the entity or taxonomy was deleted, the archive
 *   was turned off, the taxonomy was detached): it is unused.
 *
 * Rows whose slug does not have the generated shape are ignored.
 *
 * @param array<string, mixed> $config  Normalized configuration.
 * @param array<string, mixed> $context Normalized context.
 * @return array<int, array<string, mixed>> Zero, one or two checks.
 */
function glinf_dashboard_check_templates( array $config, array $context ): array {
	$generated = array();

	foreach ( $config['items'] as $entity ) {
		$post_type = glinf_entity_post_type( $entity['slug'] );

		/* translators: %s: singular name of an entity. */
		$generated[ 'single-' . $post_type ] = sprintf( __( 'Single: %s', 'gl-infinite-theme' ), $entity['singular'] );

		if ( $entity['has_archive'] ) {
			/* translators: %s: plural name of an entity. */
			$generated[ 'archive-' . $post_type ] = sprintf( __( 'Archive: %s', 'gl-infinite-theme' ), $entity['plural'] );
		}
	}

	foreach ( $config['taxonomies'] as $taxonomy ) {
		if ( array() !== $taxonomy['entities'] ) {
			/* translators: %s: plural name of a taxonomy. */
			$generated[ 'taxonomy-' . glinf_taxonomy_key( $taxonomy['slug'] ) ] = sprintf( __( 'Taxonomy: %s', 'gl-infinite-theme' ), $taxonomy['plural'] );
		}
	}

	$slugs = $context['custom_templates'];
	sort( $slugs, SORT_STRING );

	$replacing = array();
	$unused    = array();

	foreach ( $slugs as $slug ) {
		if ( 1 !== preg_match( GLINF_DASHBOARD_TEMPLATE_SLUG_REGEX, $slug, $parts ) ) {
			continue;
		}

		if ( isset( $generated[ $slug ] ) ) {
			$replacing[] = glinf_dashboard_item( $generated[ $slug ], $slug, '' );
			continue;
		}

		$unused[] = glinf_dashboard_item(
			glinf_dashboard_template_type_label( $parts[1] ),
			$slug,
			glinf_dashboard_orphan_reason( $parts[1], substr( $parts[2], strlen( GLINF_POST_TYPE_PREFIX ) ), $config )
		);
	}

	$actions = glinf_dashboard_action( __( 'Open the templates in the Site Editor', 'gl-infinite-theme' ), $context['urls']['site_editor'] );
	$checks  = array();

	if ( array() !== $replacing ) {
		$checks[] = glinf_dashboard_check(
			'custom_templates',
			'notice',
			__( 'These templates were edited in the Site Editor and replace the ones generated by the theme. Changes to the entity or taxonomy settings (fields, taxonomies, archive) do not update them. To go back to the generated version, reset the template in the Site Editor.', 'gl-infinite-theme' ),
			$replacing,
			$actions
		);
	}

	if ( array() !== $unused ) {
		$checks[] = glinf_dashboard_check(
			'orphan_templates',
			'notice',
			__( 'These saved templates no longer match anything generated by the theme, so they are not used. They are harmless: you can delete them in the Site Editor.', 'gl-infinite-theme' ),
			$unused,
			$actions
		);
	}

	return $checks;
}

/**
 * Returns the name of a kind of generated template.
 *
 * @param string $type "single", "archive" or "taxonomy".
 * @return string
 */
function glinf_dashboard_template_type_label( string $type ): string {
	return match ( $type ) {
		'single'  => __( 'Single template', 'gl-infinite-theme' ),
		'archive' => __( 'Archive template', 'gl-infinite-theme' ),
		default   => __( 'Taxonomy template', 'gl-infinite-theme' ),
	};
}

/**
 * Explains why a saved template no longer matches a generated one.
 *
 * @param string               $type   "single", "archive" or "taxonomy".
 * @param string               $slug   Slug of the entity or taxonomy the template was made for.
 * @param array<string, mixed> $config Normalized configuration.
 * @return string
 */
function glinf_dashboard_orphan_reason( string $type, string $slug, array $config ): string {
	if ( 'taxonomy' === $type ) {
		return isset( $config['taxonomies'][ $slug ] )
			? __( 'The taxonomy is not attached to any entity.', 'gl-infinite-theme' )
			: __( 'The taxonomy no longer exists.', 'gl-infinite-theme' );
	}

	return isset( $config['items'][ $slug ] )
		? __( 'The archive of this entity is turned off.', 'gl-infinite-theme' )
		: __( 'The entity no longer exists.', 'gl-infinite-theme' );
}

/**
 * Check: how close the configuration is to the limits.
 *
 * A notice from GLINF_DASHBOARD_LIMIT_NOTICE_PERCENT of the maximum, a warning
 * at the maximum. Entities and taxonomies have separate limits and separate checks.
 *
 * @param array<string, mixed> $config Normalized configuration.
 * @return array<int, array<string, mixed>> Zero, one or two checks.
 */
function glinf_dashboard_check_limits( array $config ): array {
	$checks    = array();
	$threshold = static fn( int $max ): int => (int) ceil( $max * GLINF_DASHBOARD_LIMIT_NOTICE_PERCENT / 100 );

	$entities = count( $config['items'] );
	if ( $entities >= GLINF_ENTITIES_MAX ) {
		$checks[] = glinf_dashboard_check(
			'limit_entities',
			'warning',
			sprintf(
				/* translators: %d: maximum number of entities. */
				__( 'You have reached the maximum of %d entities. To add another one, delete one you no longer need.', 'gl-infinite-theme' ),
				GLINF_ENTITIES_MAX
			)
		);
	} elseif ( $entities >= $threshold( GLINF_ENTITIES_MAX ) ) {
		$checks[] = glinf_dashboard_check(
			'limit_entities',
			'notice',
			sprintf(
				/* translators: 1: number of entities, 2: maximum number of entities. */
				__( 'You are using %1$d of %2$d entities: you are close to the limit.', 'gl-infinite-theme' ),
				$entities,
				GLINF_ENTITIES_MAX
			)
		);
	}

	$taxonomies = count( $config['taxonomies'] );
	if ( $taxonomies >= GLINF_TAXONOMIES_MAX ) {
		$checks[] = glinf_dashboard_check(
			'limit_taxonomies',
			'warning',
			sprintf(
				/* translators: %d: maximum number of taxonomies. */
				__( 'You have reached the maximum of %d taxonomies. To add another one, delete one you no longer need.', 'gl-infinite-theme' ),
				GLINF_TAXONOMIES_MAX
			)
		);
	} elseif ( $taxonomies >= $threshold( GLINF_TAXONOMIES_MAX ) ) {
		$checks[] = glinf_dashboard_check(
			'limit_taxonomies',
			'notice',
			sprintf(
				/* translators: 1: number of taxonomies, 2: maximum number of taxonomies. */
				__( 'You are using %1$d of %2$d taxonomies: you are close to the limit.', 'gl-infinite-theme' ),
				$taxonomies,
				GLINF_TAXONOMIES_MAX
			)
		);
	}

	return $checks;
}

/**
 * Runs every health check.
 *
 * Warnings come first, then notices; inside each group the order is the order in
 * which the checks are listed here. With no problem the result is an empty list
 * (the screen then shows a positive state).
 *
 * @param array<string, mixed> $config  Normalized configuration (see glinf_get_config()).
 * @param array<string, mixed> $context Facts about the site (see the file header); keys can be left out.
 * @return array<int, array{id: string, severity: string, message: string, items: array<int, array<string, mixed>>, actions: array<int, array{label: string, url: string}>}>
 */
function glinf_dashboard_get_health_checks( array $config, array $context ): array {
	$context  = glinf_dashboard_normalize_context( $context );
	$elements = glinf_dashboard_build_elements( $config );

	$checks = array(
		glinf_dashboard_check_unattached( $elements ),
		glinf_dashboard_check_url_conflicts( $elements, $context ),
		glinf_dashboard_check_rewrite_rules(
			$elements,
			$context,
			glinf_dashboard_action( __( 'Open permalink settings', 'gl-infinite-theme' ), $context['urls']['permalinks'] )
		),
		glinf_dashboard_check_plain_permalinks( $config, $context ),
	);

	$checks = array_merge( $checks, glinf_dashboard_check_templates( $config, $context ), glinf_dashboard_check_limits( $config ) );
	$checks = array_values( array_filter( $checks ) );

	// usort() is stable since PHP 8.0, so the order inside a severity is kept.
	usort(
		$checks,
		static fn( array $a, array $b ): int => ( 'warning' === $a['severity'] ? 0 : 1 ) <=> ( 'warning' === $b['severity'] ? 0 : 1 )
	);

	return $checks;
}

/**
 * Counts the checks by severity.
 *
 * @param array<int, array<string, mixed>> $checks Result of glinf_dashboard_get_health_checks().
 * @return array{warning: int, notice: int}
 */
function glinf_dashboard_count_checks( array $checks ): array {
	$counts = array(
		'warning' => 0,
		'notice'  => 0,
	);

	foreach ( $checks as $check ) {
		if ( isset( $counts[ $check['severity'] ] ) ) {
			++$counts[ $check['severity'] ];
		}
	}

	return $counts;
}
